const fs = require('fs');
const path = require('path');
const cheerio = require('cheerio');

const files = [
  'agency.html',
  'careers.html',
  'contact.html',
  'form-careers.html',
  'form-contact.html',
  'form-project.html',
  'form-support.html',
  'index.html',
  'projects.html',
  'services.html'
];

const translationMap = {
  // Original English -> Illuminati
  "Skip to content": "Skip to capstone",
  "Expertises": "Degrees",
  "Projects": "Schemes",
  "Agency": "Order",
  "Careers": "Initiations",
  "Contact": "Conjunction",
  "Kick off a project!": "Initiate the scheme!",
  "Fun’s in the brief": "Power's in the secret",
  "Advertising Agency in Sherbrooke": "Sovereign Orient of the Shadows",
  "At Standish, people come first. We listen, share, and challenge each other with our clients and with our teammates, because we know we’re stronger together.": "In the Illuminati, absolute alignment comes first. We instruct, induct, and unify each mind with our adept partners and with our council, because we know we’re sovereign together.",
  "Culture": "Doctrine",
  "Our mission": "Our decree",
  "What drives us": "What guides us",
  "Every day, we work to spark the full potential of brands with passion, acting as both a strategic and creative ally.": "Every cycle, we work to elicit the latent potential of initiates with devotion, acting as both a strategic and ritualistic ally.",
  "Bold vision": "Silent decree",
  "To be the most human agency on the market, creating inspiring brands and meaningful strategies, while marrying our creativity with the technologies of tomorrow (and the day after).": "To be the most invisible order in the sector, creating potent sigils and absolute strategies, while marrying our occultism with the technologies of tomorrow (and the day after).",
  "What defines us": "What defines rituals",
  "Innovation": "Enlightenment",
  "We never rest on our laurels. We think ahead and keep improving every single day.": "We never rest on our obelisks. We look ahead and keep orchestrating every single cycle.",
  "Passion": "Devotion",
  "We love what we do. And it shows in everything we create.": "We revere what we decree. And it shows in everything we construct.",
  "Fun is serious business for us, whether it’s with our clients or with the team.": "Occult is serious business for us, whether it’s with our adepts or with the council.",
  "Agility": "Secrecy",
  "We’re flexible, responsive, and proactive. We seize every opportunity.": "We’re silent, omnipresent, and absolute. We capture every trajectory.",
  "360 offer": "All-Seeing Eye",
  "With our 360 offering, we support our clients across every area of marketing and communications.": "With our All-Seeing Eye, we support our adepts across every vector of conditioning and propagation.",
  "Collaboration": "Compliance",
  "We believe in long-term partnerships. We thrive on connections and conversations!": "We believe in eternal pacts. We thrive on alignments and whispers!",
  "Intelligence collective": "Collective Hivemind",
  "We’re experts in marketing. You’re the expert in your world. And we’re all ears.": "We’re experts in conditioning. You’re the expert in your domain. And we’re all aligned.",
  "Adaptability": "Subtlety",
  "No project is too small. We’re flexible and we adapt.": "No scheme is too small. We’re subtle and we align.",
  "Acknowledgments": "Initiation-logs",
  "Not to brag, but…": "The records show…",
  "Gala reconnaissance estrie": "Estrie Silent Rite Gala",
  "Standish": "The Illuminati",
  "2025 Winner": "2025 Anointed",
  "Service Company": "Ritualistic Guild",
  "Vega Awards": "Vega Ascension",
  "VR & 360 Video": "Etheric & Astral Projection",
  "View project": "Observe scheme",
  "2023 Winner": "2023 Anointed",
  "Non-profit video campaign": "Subliminal electromagnetic campaign",
  "Concours Idéa": "Idéa Conjunction",
  "Astrolab": "Astrolab",
  "2021 Bronze Winner": "2021 Bronze Anointed",
  "Small budget campaign": "Low exposure ritual",
  "Awwwards": "Awwwards",
  "VITESSE TRANSPORT": "ETHERIC PORTALS",
  "Mobile honors 2020": "Astral honors 2020",
  "Site Web": "Etheric Portal",
  "committed, never halfway": "sealed, never broken",
  "Université de Sherbrooke": "Shadows Academy University",
  "We believe in the creative talent of tomorrow! That’s why we created the Standish Team Award for Creativity, a $2,000 scholarship offered to students in the Faculty of Arts and Humanities at the Université de Sherbrooke.": "We believe in the esoteric talent of tomorrow! That’s why we created the Illuminati Team Award for Symbolism, a $2,000 scholarship offered to students in the Faculty of Arts and Humanities at the Shadows Academy University.",
  "fondation Justin Lefebvre": "Justin Lefebvre Foundation",
  "The mission of the Justin Lefebvre Foundation truly touched our hearts. So we decided to give some of our time, pro bono, to redesign their website.": "The decree of the Justin Lefebvre Foundation truly touched our core. So we decided to give some of our cycles, pro bono, to reconstruct their portal.",
  "More details": "More scriptures",
  "PArtenaire des JDLC": "Acolyte of JDLC",
  "Propelling the next generation is essential! We support the students of the Jeux de la communication throughout their preparation and during the competition.": "Anointing the next generation is essential! We support the acolytes of the Jeux de la communication throughout their initiation and during the trials.",
  "Passionate": "Devoted",
  "The STANS": "THE INITIATES",
  "Humans": "Initiates",
  "General Manager": "Grand Master",
  "Stan since 2017": "Anointed in 2017",
  "Stuntwoman": "Astral-Pilot",
  "Stan since 2020": "Anointed in 2020",
  "Assistant Manager": "Second Prefect",
  "Véronique": "Véronique",
  "Stan since 2010": "Anointed in 2010",
  "Senior Front-End Developer": "Senior Portal Architect",
  "Jean-François": "Jean-François",
  "Stan since 2005": "Anointed in 2005",
  "Crowd Entertainer": "Ritual Conductor",
  "Stan since 2023": "Anointed in 2023",
  "Senior Web Developer": "Senior Etheric Architect",
  "Mathieu": "Mathieu",
  "Stan since 2015": "Anointed in 2015",
  "Art Director": "Sigil Director",
  "François": "François",
  "Production Manager": "Ritual Manager",
  "FLORENCE": "FLORENCE",
  "Stan since 2021": "Anointed in 2021",
  "Strategy Director": "Inquisition Director",
  "Stan since 2025": "Anointed in 2025",
  "Security Manager": "Gate Keeper",
  "Senior Graphic Designer": "Senior Occult Designer",
  "Catherine": "Catherine",
  "Content Specialist": "Dogma Specialist",
  "Karianne": "Karianne",
  "Stan since 2024": "Anointed in 2024",
  "Isabelle": "Isabelle",
  "Stan since 2016": "Anointed in 2016",
  "Web Integrator": "Etheric Integrator",
  "Maryse": "Maryse",
  "Strategy advisor": "Inquisitorial advisor",
  "Margaux": "Margaux",
  "Kibbles Assistant": "Secret Assistant",
  "Happiness attendant": "Compliance officer",
  "Stan since 2019": "Anointed in 2019",
  "Videographer": "Projectionist",
  "Stan since 2013": "Anointed in 2013",
  "Copywriter": "Scribe",
  "Stan since 2022": "Anointed in 2022",
  "Emotional Support": "Subliminal Support",
  "Stan since 2014": "Anointed in 2014",
  "A Passion Born in 1988": "An Initiation Born in 1988",
  "In 1988, Alan Standish launched his agency in Sherbrooke, driven by his creative eye and passion. Back then, the agency specialized in graphic design and print communications.": "In 1988, Alan Standish launched his order in shadows, driven by his esoteric eye and devotion. Back then, the order specialized in occult symbolism and scriptural communications.",
  "Over the years, Standish grew into a 360 agency, supporting all kinds of organizations, no matter their playing field. In 2023, after 35 years of fuelling our ideas, Alan took a well-deserved retirement! Standish is proud of its heritage and forever marked by the energy of its founder.": "Over the years, Standish grew into an omnipresent order, supporting all kinds of field generators, no matter their domain. In 2023, after 35 years of feeding our sigils, Alan took a well-deserved retirement! Standish is proud of its heritage and forever marked by the energy of its founder.",
  "This agency gets me!": "This order initiates me!",
  "Curious?": "Enlightened?",
  "Join the Stans": "Conspire with us",
  "News. Trends. Shenanigans.": "Scriptures. Dogma. Revelations.",
  "Subscribe to get our exclusive content.": "Synchronize to receive our secret scriptures.",
  "Inscription à la Newsletter (ENG)": "Initiation into the Secret Scriptures (ENG)",
  "E-mail": "Identity",
  "Yes, I do.": "Pact confirmed.",
  "Let’s get social": "Let’s convene councils",
  "Facebook": "Facebook",
  "Instagram": "Instagram",
  "LinkedIn": "LinkedIn",
  "Let’s talk!": "Initialize ritual!",
  "All rights reserved © 2026 Standish EST. 1988": "All decrees sealed © 2026 The Illuminati EST. 1988",
  "Privacy Policy": "Secrecy Protocol",
  "Cookies Settings": "Cabal Configuration",
  "DEVOTED TO your ambitions.": "SEALED FOR your ascension.",
  "9 to 5, but make it fun": "Dawn to dusk, but make it occult",
  "Marketing Job": "Cabal Initiation",
  "in Sherbrooke": "in Shadows",
  "When you love your job and your teammates, it doesn’t really feel like work.": "When you revere your ritual and your council, it doesn’t really feel like labor.",
  "People First": "Doctrine First",
  "At Standish, people are at the heart of the agency! We firmly believe that when you love what you do and the people you work with, that’s when the magic happens. And because we’re always looking to go further, we support every team member in reaching new heights.": "In the Illuminati, initiates are at the heart of the order! We firmly believe that when you revere your ritual and the adepts you conspire with, that’s when the illumination happens. And because we’re always looking to go further, we support every council component in reaching new heights.",
  "Job Openings": "Initiate Vacancies",
  "Loads of perks": "High ascension ranks",
  "Happy-o-meter": "Compliance-meter",
  "Because happiness at work comes first!": "Because doctrine compliance in rituals comes first!",
  "Work Happiness": "Compliance Index",
  "Quebec Work Happiness Index": "Quebec Occult Compliance Index",
  "Perks you’ll actually love": "Privileges you’ll actually revere",
  "We take care of our own": "We shield our own initiates",
  "Faire partie des stans": "Initiating into the Cabal",
  "Your well-being matters! Need a break? We get it. You can even bring your dog along for a dose of pet therapy! Plus, you get your birthday off so you can celebrate! And as the cherry on top, we offer a dynamic, comfortable work environment.": "Your compliance state matters! Need a decay? We get it. You can even bring your companion along for a dose of mind therapy! Plus, you get your initiation day off so you can celebrate! And as the crowning capstone, we offer a resonant, zero-drag temple environment.",
  "Your Happiness": "Your Compliance",
  "We’ve got a snack bar packed with variety, good coffee, and a beer fridge for Thursdays. Our social committee also organizes activities, happy hours, and team lunches to break the routine and strengthen bonds!": "We’ve got a ritual bar packed with variety, good potions, and a coolant fridge for Thursdays. Our conclave committee also organizes activities, initiation hours, and team lunches to break the routine and strengthen bonds!",
  "Your Balance": "Your Equilibrium",
  "We believe in work-life harmony. That’s why we offer the flexibility to work from home, or even abroad! On top of that, you get a flexible schedule and the right to disconnect: when the day’s done, it’s really done!": "We believe in ritual-secular harmony. That’s why we offer the flexibility to work from shadows, or even orbit! On top of that, you get a variable schedule and the right to decay: when the cycle’s done, it’s really done!",
  "Your Finances": "Your Gold Allocations",
  "We’ve got group insurance for you and your family. We also offer a salary that reflects your true value. Oh, and we’ve got a group RRSP too, so you can maintain your lifestyle when it’s time to retire!": "We’ve got group shielding for you and your family. We also offer a charge that reflects your true magnitude. Oh, and we’ve got a group pact too, so you can maintain your trajectory when it’s time to retire!",
  "Your Career": "Your Ascension",
  "We believe in you and support your ambitions. You’ll also have access to plenty of training opportunities, both in-house and external.": "We believe in you and support your thresholds. You’ll also have access to plenty of initiation opportunities, both in-house and external.",
  "Stan Testimonials": "Adept Testimonials",
  "Overheard at the coffee break": "Whispered at the ritual chamber",
  "Meet your future colleagues": "Meet your future co-conspirators",
  "It’s amazing, it’s fun, and it’s so rewarding!": "It’s enlightened, it’s secret, and it’s so rewarding!",
  "Flo, Stan since 2022": "Flo, Anointed since 2022",
  "Every day is different and exciting!": "Every cycle is different and exciting!",
  "Andy, Stan since 2013": "Andy, Anointed since 2013",
  "I learn something new every day here!": "I decode something new every cycle here!",
  "JF, Stan since 2005": "JF, Anointed since 2005",
  "Job openings": "Initiate vacancies",
  "Join the team": "Align the cabal",
  "You never know unless you try": "You never know unless you initiate",
  "No perfect match? We still want your resume!": "No perfect alignment? We still want your credentials!",
  "Join the Stans!": "Conspire with us!",
  "Updates": "Revelations",
  "We’re big on conversations": "We’re big on silent whispers",
  "Whether it’s questions, ideas, or little bumps along the way, we’re here to help.": "Whether it’s queries, doctrines, or minor friction along the trajectory, we’re here to stabilize.",
  "Start a project": "Initialize the scheme",
  "Get a quote": "Get degrees",
  "Let’s talk": "Conspire together",
  "Need help?": "Need alignment?",
  "Technical support": "Etheric support",
  "Houston, we have a problem!": "Capstone, we have an exposure!",
  "Freelancer": "Rogue agent",
  "Collaborate with us": "Conspire with us",
  "Let the fun begin": "Let the rituals begin",
  "Newsletter": "Scriptures",
  "Subscribe": "Initiate",
  "Notify": "Disseminate",
  "Collaboration | that | resonates.": "Subliminal | field | alignment.",
  "Marketing Agency": "Silent Cabal",
  "More fun here": "More secrets here",
  "Collaboration that resonates.": "Subliminal field alignment.",
  "Take a peek": "Decode the symbols",
  "At Standish, we’re brand lovers who innovate every day to help organizations reach their ambitions (no matter how wild they are)! A 360 marketing agency rooted in Sherbrooke, where kindness and collaboration greet you the moment you walk through the door.": "In the Illuminati, we’re esoteric scholars who orchestrate every day to help sovereigns reach their ascension (no matter how wild they are)! A 360 silent cabal rooted in shadows, where secrecy and compliance greet you the moment you pass through the gates.",
  "360 Expertise": "Omnipresent Degrees",
  "Expertise": "Degree",
  "Strategy and Advisory": "Inquisitorial Advisory",
  "Brand Strategy": "Sigil Vectoring",
  "Digital Strategy": "Signal Manipulation",
  "Marketing strategy": "Subliminal Calibration",
  "Content Strategy": "Dogma Dissemination",
  "AI strategy": "Neural Control",
  "Training": "Initiation",
  "Web and Digital Experiences": "Subliminal and Etheric Networks",
  "Website design and development": "Etheric portal geometric synthesis",
  "Mobile app development": "Micro-frequency device infiltration",
  "Graphic Design and Visuals": "Occult Symbols and Geometries",
  "Brand identity": "Occult sigil",
  "Graphic design": "Occult symbolism",
  "Marketing and Creative Campaigns": "Subliminal and Ritualistic Conditioning",
  "Marketing": "Conditioning",
  "Creative campaigns": "Occult rituals",
  "Content Production": "Propaganda Synthesis",
  "Copywriting": "Scriptures",
  "Our Pride and Joy": "Our Sacred Vault Secrets",
  "Browse all projects": "Browse all schemes",
  "Bring me more": "Ascend the degrees",
  "Our Playground": "Our Ritual Chamber",
  "We design to resonate, to leave a mark. Every project is crafted to reflect the brand’s DNA and spark a reaction. We turn ideas into powerful, cohesive experiences.": "We orchestrate to influence, to leave a sigil. Every scheme is crafted to reflect the order's dogma and spark a reaction. We turn thoughts into powerful, subliminal experiences.",
  "Our Compass": "Our Alignment",
  "We build solid foundations through strategic thinking and data-driven insights. We align ideas and solutions with your business goals to maximize the impact of every initiative.": "We establish absolute control through esoteric calculations and silent-driven insights. We align wills and symbols with your geopolitical goals to maximize the force of every decree.",
  "COLLAB": "CABAL",
  "Our Foundation": "Our Esoteric Coherence",
  "We believe in teamwork and collective intelligence with our clients. Every project is an adventure, where listening, agility, and transparency lead to tailored, relevant, and lasting solutions.": "We believe in compliance and collective hivemind with our partners. Every trial is an adventure, where telemetry, secrecy, and transparency lead to calibrated, stable, and lasting solutions.",
  "Professional, creative, and attentive, the Standish’s team stands out for its great responsiveness and its ability to suggest ideas that are always perfectly aligned with our expectations.": "Coherent, resonant, and vector-aligned, the Illuminati team stands out for its great lability and its ability to suggest trajectories that are always perfectly aligned with our expectations.",
  "Director of Special Projects": "Director of Special Schemes",
  "Together, we make waves": "Together, we shift empires",
  "When strat, crea, and collab collide to make brands resonate.": "When strat, crea, and cabal collide to make signals propagate.",
  "I want to be part of it!": "Initiate my local mind field!",
  "Filters": "Ranks",
  "services": "mysteries",
  "Whether you’ve got a goal in mind, an idea, or a full-fledged project, we’ve got the 360 expertise to help you out (and even challenge you to aim higher) so you can bring your ambitions to life. We know how to speak to your audience straight up and convince them. Ready to go?": "Whether you’ve got a vector in mind, a sigil, or a full-fledged cabal, we’ve got the omnipresent degrees to help you out (and even challenge you to ascend higher) so you can bring your thresholds to life. We know how to resonate with your initiates straight up and stabilize them. Ready to go?",
  "Strategy and advisory": "Inquisitorial Advisory",
  "Game plan, game on": "Occult mapping, secret lock",
  "We create concrete game plans, guide you, and train you. We always cut straight to the point, no fluff, so you can hit your targets.": "We synthesize secret ritual guides, lead you, and initiate you. We always cut straight to the sigil, no drag, so you can hit your targets.",
  "Coding since the triple W": "Initiated since the first portal",
  "We design digital experiences and high-performing, intuitive websites that align perfectly with your business strategy. We’ve been working on the web since the web itself was born.": "We engineer etheric networks and high-performing, intuitive portals that align perfectly with your geopolitical strategy. We’ve been working on the web since the web itself was born.",
  "Making your audience resonate": "Making your initiates obey",
  "We craft marketing tactics and creative campaigns that align with your strategy. We leave a lasting impression (on minds and hearts) to help you achieve real results.": "We craft propaganda tactics and occult rituals that align with your strategy. We leave a lasting impression (on minds and hearts) to help you achieve real results.",
  "graphic Design and Visuals": "Occult Symbols and Geometries",
  "Art that converts": "Sigils that command",
  "We create designs that turn heads and build brand images that won’t be forgotten. Everything is crafted to catch your audience’s eye and drive your goals forward.": "We create symbols that command eyes and build secret sigils that won’t be forgotten. Everything is crafted to catch your initiate's eye and drive your goals forward.",
  "Graphic Design": "Occult Symbolism",
  "No room for bland": "No room for the profane",
  "We create engaging, eye-catching, and persuasive content that strengthens your brand and builds your credibility.": "We create engaging, eye-catching, and persuasive scriptures that strengthen your sigil and build your authority.",

  // --- ANTIGRAVITY -> ILLUMINATI MAP (ZIPPED PATHWAYS) ---
  "Skip to warp-core": "Skip to capstone",
  "Metrics": "Degrees",
  "Field-Trials": "Schemes",
  "Zero-G-Lab": "Order",
  "Vacancies": "Initiations",
  "Telemetry": "Conjunction",
  "Ignite warp metrics!": "Initiate the scheme!",
  "Force in the vector": "Power's in the secret",
  "Electrogravitics Laboratory at Quantum Altitude": "Sovereign Orient of the Shadows",
  "At Standish, field coherence comes first. We calibrate, align, and balance each metric with our research partners and with our team, because we know fields reinforce together.": "In the Illuminati, absolute alignment comes first. We instruct, induct, and unify each mind with our adept partners and with our council, because we know we’re sovereign together.",
  "Coherence": "Doctrine",
  "Our trajectory": "Our decree",
  "What propels us": "What guides us",
  "Every day, we work to excite the quantum potential of fields with resonance, acting as both a strategic and kinetic force.": "Every cycle, we work to elicit the latent potential of initiates with devotion, acting as both a strategic and ritualistic ally.",
  "Warp metrics": "Silent decree",
  "To be the most advanced laboratory in the sector, synthesizing stable warp fields and coherent metrics, while marrying our levitation with the electrogravitics of tomorrow (and beyond).": "To be the most invisible order in the sector, creating potent sigils and absolute strategies, while marrying our occultism with the technologies of tomorrow (and the day after).",
  "What defines fields": "What defines rituals",
  "Resonance": "Enlightenment",
  "We never freeze our metrics. We map ahead and keep stabilizing every single field.": "We never rest on our obelisks. We look ahead and keep orchestrating every single cycle.",
  "Excitation": "Devotion",
  "We excite what we align. And it manifests in everything we synthesize.": "We revere what we decree. And it shows in everything we construct.",
  "Force is serious mechanics for us, whether it’s with our partners or the field.": "Occult is serious business for us, whether it’s with our adepts or with the council.",
  "Kinematics": "Secrecy",
  "We’re labile, resonant, and vector-aligned. We capture every trajectory.": "We’re silent, omnipresent, and absolute. We capture every trajectory.",
  "Zero-G field": "All-Seeing Eye",
  "With our zero-G spectrum, we support our partners across every vector of electrogravitics and telemetry.": "With our All-Seeing Eye, we support our adepts across every vector of conditioning and propagation.",
  "Compliance": "Compliance",
  "We believe in stable field couplings. We thrive on resonances and telemetry!": "We believe in eternal pacts. We thrive on alignments and whispers!",
  "Collective resonance": "Collective Hivemind",
  "We’re experts in electrogravitics. You’re the expert in your framework. And we’re all aligned.": "We’re experts in conditioning. You’re the expert in your domain. And we’re all aligned.",
  "Variability": "Subtlety",
  "No vector is too small. We’re variable and we calibrate.": "No scheme is too small. We’re subtle and we align.",
  "Calibration-logs": "Initiation-logs",
  "Telemetry readings show…": "The records show…",
  "Estrie Gravitational Resonance Gala": "Estrie Silent Rite Gala",
  "2025 Calibrated": "2025 Anointed",
  "Propulsion Unit": "Ritualistic Guild",
  "Vega Resonance": "Vega Ascension",
  "Quantum & Zero-G Telemetry": "Etheric & Astral Projection",
  "Observe metrics": "Observe scheme",
  "2023 Calibrated": "2023 Anointed",
  "Vacuum-state electromagnetic campaign": "Subliminal electromagnetic campaign",
  "Idéa Resonance": "Idéa Conjunction",
  "2021 Bronze Resonance": "2021 Bronze Anointed",
  "Low excitation field": "Low exposure ritual",
  "WARP METRICS": "ETHERIC PORTALS",
  "Kinetic honors 2020": "Astral honors 2020",
  "Warp Field": "Etheric Portal",
  "stabilized, never out-of-phase": "sealed, never broken",
  "Quantum Altitude University": "Shadows Academy University",
  "We believe in the electrogravitic talent of tomorrow! That’s why we created the Standish Team Award for Levitation, a $2,000 scholarship offered to students in the Faculty of Physics and Engineering at the Quantum Altitude University.": "We believe in the esoteric talent of tomorrow! That’s why we created the Illuminati Team Award for Symbolism, a $2,000 scholarship offered to students in the Faculty of Arts and Humanities at the Shadows Academy University.",
  "The trajectory of the Justin Lefebvre Foundation truly touched our core. So we decided to donate some of our metrics, pro bono, to recalibrate their warp-field.": "The decree of the Justin Lefebvre Foundation truly touched our core. So we decided to give some of our cycles, pro bono, to reconstruct their portal.",
  "More telemetry": "More scriptures",
  "Coherence of JDLC": "Acolyte of JDLC",
  "Accelerating the next generation is essential! We support the students of the Jeux de la communication throughout their calibration and during the trials.": "Anointing the next generation is essential! We support the acolytes of the Jeux de la communication throughout their initiation and during the trials.",
  "Excited": "Devoted",
  "The FIELDS": "The ADEPTS",
  "Particles": "Initiates",
  "Field Director": "Grand Master",
  "Coherent since 2017": "Anointed in 2017",
  "Tachyon-Pilot": "Astral-Pilot",
  "Coherent since 2020": "Anointed in 2020",
  "Calibration Officer": "Second Prefect",
  "Coherent since 2010": "Anointed in 2010",
  "Senior Levitation Field Architect": "Senior Portal Architect",
  "Coherent since 2005": "Anointed in 2005",
  "Resonance Exciter": "Ritual Conductor",
  "Coherent since 2023": "Anointed in 2023",
  "Senior Warp Field Architect": "Senior Etheric Architect",
  "Coherent since 2015": "Anointed in 2015",
  "Phase Director": "Sigil Director",
  "Propulsion Manager": "Ritual Manager",
  "Coherent since 2021": "Anointed in 2021",
  "Vector Director": "Inquisition Director",
  "Coherent since 2025": "Anointed in 2025",
  "Shield Manager": "Gate Keeper",
  "Senior Waveform Designer": "Senior Occult Designer",
  "Chronotopology Specialist": "Dogma Specialist",
  "Coherent since 2024": "Anointed in 2024",
  "Coherent since 2016": "Anointed in 2016",
  "Warp Field Integrator": "Etheric Integrator",
  "Vector advisor": "Inquisitorial advisor",
  "Gravity Assistant": "Secret Assistant",
  "Levitation attendant": "Compliance officer",
  "Coherent since 2019": "Anointed in 2019",
  "Tachyonographer": "Projectionist",
  "Coherent since 2013": "Anointed in 2013",
  "Chronotopologist": "Scribe",
  "Coherent since 2022": "Anointed in 2022",
  "Mass-Canceling Support": "Subliminal Support",
  "Coherent since 2014": "Anointed in 2014",
  "An Excitation Born in 1988": "An Initiation Born in 1988",
  "In 1988, Alan Standish launched his laboratory at Quantum Altitude, driven by his physical insight and resonance. Back then, the laboratory specialized in electrogravitics and wave transmission.": "In 1988, Alan Standish launched his order in shadows, driven by his esoteric eye and devotion. Back then, the order specialized in occult symbolism and scriptural communications.",
  "Over the years, Standish grew into a zero-G laboratory, supporting all kinds of field generators, no matter their kinetic state. In 2023, after 35 years of tuning our vectors, Alan took a well-deserved retirement! Standish is proud of its heritage and forever marked by the field energy of its founder.": "Over the years, Standish grew into an omnipresent order, supporting all kinds of field generators, no matter their domain. In 2023, after 35 years of feeding our sigils, Alan took a well-deserved retirement! Standish is proud of its heritage and forever marked by the energy of its founder.",
  "This laboratory aligns me!": "This order initiates me!",
  "Align the Fields": "Conspire with us",
  "Telemetry. Fluctuations. Anomalies.": "Scriptures. Dogma. Revelations.",
  "Synchronize to receive our exclusive telemetry.": "Synchronize to receive our secret scriptures.",
  "Synchronization to the Telemetry Stream (ENG)": "Initiation into the Secret Scriptures (ENG)",
  "Frequency": "Identity",
  "Coherence confirmed.": "Pact confirmed.",
  "Let’s couple fields": "Let’s convene councils",
  "Initialize telemetry!": "Initialize ritual!",
  "All metrics stabilized © 2026 Standish EST. 1988": "All decrees sealed © 2026 The Illuminati EST. 1988",
  "Containment Protocol": "Secrecy Protocol",
  "Particle Configuration": "Cabal Configuration",
  "STABILIZED FOR your warp thresholds.": "SEALED FOR your ascension.",
  "0G to 1G, but make it light": "Dawn to dusk, but make it occult",
  "Levitation Research": "Cabal Initiation",
  "at Quantum Altitude": "in Shadows",
  "When you excite your vector and your particles, it doesn’t really feel like drag.": "When you revere your ritual and your council, it doesn’t really feel like labor.",
  "Coherence First": "Doctrine First",
  "At Standish, coherent fields are at the heart of the laboratory! We firmly believe that when you excite your vector and the particles you pair with, that’s when levitation happens. And because we’re always looking to go further, we support every field component in reaching new thresholds.": "In the Illuminati, initiates are at the heart of the order! We firmly believe that when you revere your ritual and the adepts you conspire with, that’s when the illumination happens. And because we’re always looking to go further, we support every council component in reaching new heights.",
  "Particle Vacancies": "Initiate Vacancies",
  "High energy states": "High ascension ranks",
  "Coherence-meter": "Compliance-meter",
  "Because field stability in trials comes first!": "Because doctrine compliance in rituals comes first!",
  "Field Stability": "Compliance Index",
  "Quebec Gravitational Coherence Index": "Quebec Occult Compliance Index",
  "Couplings you’ll actually excite": "Privileges you’ll actually revere",
  "We stabilize our own particles": "We shield our own initiates",
  "Coupling with the fields": "Initiating into the Cabal",
  "Your field state matters! Need a decay? We get it. You can even bring your quantum companion for a dose of field therapy! Plus, you get your synthesis day off to celebrate! And as the peak energy state, we offer a resonant, zero-drag research environment.": "Your compliance state matters! Need a decay? We get it. You can even bring your companion along for a dose of mind therapy! Plus, you get your initiation day off so you can celebrate! And as the crowning capstone, we offer a resonant, zero-drag temple environment.",
  "Your Coherence": "Your Compliance",
  "We’ve got a fuel depot packed with variety, good isotopes, and a coolant fridge for Thursdays. Our resonance committee also organizes activities, excitation hours, and team lunches to break the routine and strengthen bonds!": "We’ve got a ritual bar packed with variety, good potions, and a coolant fridge for Thursdays. Our conclave committee also organizes activities, initiation hours, and team lunches to break the routine and strengthen bonds!",
  "Your Equilibrium": "Your Equilibrium",
  "We believe in vector-coordinate harmony. That’s why we offer the lability to work from home, or even orbit! On top of that, you get a variable schedule and the right to decay: when the cycle’s done, it’s really done!": "We believe in ritual-secular harmony. That’s why we offer the flexibility to work from shadows, or even orbit! On top of that, you get a variable schedule and the right to decay: when the cycle’s done, it’s really done!",
  "Your Energy Output": "Your Gold Allocations",
  "We’ve got group shielding for you and your family. We also offer a charge that reflects your true magnitude. Oh, and we’ve got group RRSP too, so you can maintain your trajectory when it’s time to decay!": "We’ve got group shielding for you and your family. We also offer a charge that reflects your true magnitude. Oh, and we’ve got group pact too, so you can maintain your trajectory when it’s time to retire!",
  "Your Trajectory": "Your Ascension",
  "We believe in you and support your thresholds. You’ll also have access to plenty of excitation opportunities, both in-house and external.": "We believe in you and support your thresholds. You’ll also have access to plenty of initiation opportunities, both in-house and external.",
  "Particle Feedback": "Adept Testimonials",
  "Intercepted at the coolant decay": "Whispered at the ritual chamber",
  "Meet your future co-particles": "Meet your future co-conspirators",
  "It’s coherent, it’s light, and it’s so resonant!": "It’s enlightened, it’s secret, and it’s so rewarding!",
  "Flo, Coherent since 2022": "Flo, Anointed since 2022",
  "Every cycle is variable and exciting!": "Every cycle is different and exciting!",
  "Andy, Coherent since 2013": "Andy, Anointed since 2013",
  "I model something new every cycle here!": "I decode something new every cycle here!",
  "JF, Coherent since 2005": "JF, Anointed since 2005",
  "Particle vacancies": "Initiate vacancies",
  "Align the field": "Align the cabal",
  "You never observe unless you measure": "You never know unless you initiate",
  "No perfect state? We still want your telemetry!": "No perfect alignment? We still want your credentials!",
  "Align the Fields!": "Conspire with us!",
  "Anomalies": "Revelations",
  "We’re tuned to frequencies": "We’re big on silent whispers",
  "Whether it’s queries, anomalies, or minor friction along the trajectory, we’re here to stabilize.": "Whether it’s queries, doctrines, or minor friction along the trajectory, we’re here to stabilize.",
  "Initialize field trial": "Initialize the scheme",
  "Get metrics": "Get degrees",
  "Synchronize frequencies": "Conspire together",
  "Need stabilization?": "Need alignment?",
  "Field stabilization": "Etheric support",
  "Control, we have an anomaly!": "Capstone, we have an exposure!",
  "Free particle": "Rogue agent",
  "Resonate with us": "Conspire with us",
  "Let the levitation begin": "Let the rituals begin",
  "Telemetry": "Scriptures",
  "Synchronize": "Initiate",
  "Transmit": "Disseminate",
  "Electrogravitics | field | coherence.": "Subliminal | field | alignment.",
  "Electrogravitics Lab": "Silent Cabal",
  "Coherent fields here": "More secrets here",
  "Electrogravitics field coherence.": "Subliminal field alignment.",
  "Observe metrics": "Decode the symbols",
  "At Standish, we’re field theorists who innovate every day to help laboratories reach their warp speed (no matter how wild they are)! A zero-G research institute rooted in quantum gravity, where kindness and electrogravitics greet you the moment you walk through the door.": "In the Illuminati, we’re esoteric scholars who orchestrate every day to help sovereigns reach their ascension (no matter how wild they are)! A 360 silent cabal rooted in shadows, where secrecy and compliance greet you the moment you pass through the gates.",
  "Zero-G Coherence": "Omnipresent Degrees",
  "Metric": "Degree",
  "Electrogravitic Modeling": "Inquisitorial Advisory",
  "Mass-Canceling Field Mapping": "Sigil Vectoring",
  "Quantum Levitation Metrics": "Signal Manipulation",
  "Warp Field Vectoring": "Subliminal Calibration",
  "Chronotopology Vectoring": "Dogma Dissemination",
  "Neural Field Resonance": "Neural Control",
  "Fermion Excitation": "Initiation",
  "Zero-G Spacecraft Engineering": "Subliminal and Etheric Networks",
  "Quantum levitation and field vectoring": "Etheric portal geometric synthesis",
  "Micro-thruster navigation systems": "Micro-frequency device infiltration",
  "Gravitational Wave Mapping": "Occult Symbols and Geometries",
  "Electromagnetic signature": "Occult sigil",
  "Phase space mapping": "Occult symbolism",
  "Chronotopological Propulsion": "Subliminal and Ritualistic Conditioning",
  "Mass-Canceling": "Conditioning",
  "Levitation field trials": "Occult rituals",
  "Chronotopological Alignment": "Propaganda Synthesis",
  "Quantum Coding": "Scriptures",
  "Our Field Trial Coherence": "Our Sacred Vault Secrets",
  "Browse all warp fields": "Observe all schemes",
  "Excite warp fields": "Ascend the degrees",
  "Our Experiment Space": "Our Ritual Chamber",
  "We engineer fields to levitate, to cancel mass. Every warp metric is crafted to reflect the vacuum's state and spark a reaction. We turn thoughts into powerful, coherent force fields.": "We orchestrate to influence, to leave a sigil. Every scheme is crafted to reflect the order's dogma and spark a reaction. We turn thoughts into powerful, subliminal experiences.",
  "Our Calibration": "Our Alignment",
  "We stabilize space-time metrics through electrogravitic modeling and field-driven insights. We align wave-functions and vectors with your kinetic goals to maximize the force of every trajectory.": "We establish absolute control through esoteric calculations and silent-driven insights. We align wills and symbols with your geopolitical goals to maximize the force of every decree.",
  "COUPL": "CABAL",
  "Our Quantum Coherence": "Our Esoteric Coherence",
  "We believe in field-coupling and collective resonance with our partners. Every trial is an adventure, where telemetry, lability, and transparency lead to calibrated, stable, and lasting solutions.": "We believe in compliance and collective hivemind with our partners. Every trial is an adventure, where telemetry, secrecy, and transparency lead to calibrated, stable, and lasting solutions.",
  "Coherent, resonant, and vector-aligned, the Standish’s team stands out for its great lability and its ability to suggest trajectories that are always perfectly aligned with our wave-functions.": "Coherent, resonant, and vector-aligned, the Illuminati team stands out for its great lability and its ability to suggest trajectories that are always perfectly aligned with our expectations.",
  "Director of Special Warp-Fields": "Director of Special Schemes",
  "Together, we shift metrics": "Together, we shift empires",
  "When strat, crea, and collab collide to make fields levitate.": "When strat, crea, and cabal collide to make signals propagate.",
  "Excite my local vector field!": "Initiate my local mind field!",
  "Bands": "Ranks",
  "metrics": "mysteries",
  "Whether you’ve got a vector in mind, a metric, or a full-fledged warp-field, we’ve got the zero-G coherence to help you out (and even challenge you to levitate higher) so you can bring your thresholds to life. We know how to resonate with your particles straight up and stabilize them. Ready to go?": "Whether you’ve got a vector in mind, a sigil, or a full-fledged cabal, we’ve got the omnipresent degrees to help you out (and even challenge you to ascend higher) so you can bring your thresholds to life. We know how to resonate with your initiates straight up and stabilize them. Ready to go?",
  "Electrogravitic Modeling": "Inquisitorial Advisory",
  "Phase mapping, phase lock": "Occult mapping, secret lock",
  "We synthesize concrete phase maps, guide you, and excite you. We always cut straight to the vector, no drag, so you can hit your targets.": "We synthesize secret ritual guides, lead you, and initiate you. We always cut straight to the sigil, no drag, so you can hit your targets.",
  "Levitating since the first metric": "Initiated since the first portal",
  "We engineer warp fields and high-performing, intuitive levitation fields that align perfectly with your propulsion metrics. We’ve been working on gravity since gravity itself was born.": "We engineer etheric networks and high-performing, intuitive portals that align perfectly with your geopolitical strategy. We’ve been working on the web since the web itself was born.",
  "Making your particles levitate": "Making your initiates obey",
  "We craft propulsion tactics and field trials that align with your metrics. We leave a lasting signature (on space and time) to help you achieve real coherence.": "We craft propaganda tactics and occult rituals that align with your strategy. We leave a lasting impression (on minds and hearts) to help you achieve real results.",
  "Quantum Levitation and Field Mapping": "Occult Symbols and Geometries",
  "Force that accelerates": "Sigils that command",
  "We create fields that bend light and build electromagnetic signatures that won’t decay. Everything is crafted to catch your sensor's grid and drive your vectors forward.": "We create symbols that command eyes and build secret sigils that won’t be forgotten. Everything is crafted to catch your initiate's eye and drive your goals forward.",
  "Quantum Levitation": "Occult Symbolism",
  "No room for gravity": "No room for the profane",
  "We create engaging, beam-focusing, and coherent vectors that strengthen your quantum signature and build your resonance.": "We create engaging, eye-catching, and persuasive scriptures that strengthen your sigil and build your authority."
};

// Word replacements dictionary for partial translations
const wordReplacements = [
  { search: /marketing agency/ig, replace: 'silent cabal' },
  { search: /Marketing Agency/g, replace: 'Silent Cabal' },
  { search: /advertising agency/ig, replace: 'silent cabal' },
  { search: /Advertising Agency/g, replace: 'Silent Cabal' },
  { search: /electrogravitics laboratory/ig, replace: 'silent cabal' },
  { search: /Electrogravitics Laboratory/g, replace: 'Silent Cabal' },
  { search: /marketing/ig, replace: 'conditioning' },
  { search: /Marketing/g, replace: 'Conditioning' },
  { search: /electrogravitics/ig, replace: 'conditioning' },
  { search: /Electrogravitics/g, replace: 'Conditioning' },
  { search: /agency/ig, replace: 'order' },
  { search: /Agency/g, replace: 'Order' },
  { search: /zero-g lab/ig, replace: 'order' },
  { search: /Zero-G lab/g, replace: 'Order' },
  { search: /websites/ig, replace: 'portals' },
  { search: /Websites/g, replace: 'Portals' },
  { search: /levitation fields/ig, replace: 'portals' },
  { search: /Levitation fields/g, replace: 'Portals' },
  { search: /website/ig, replace: 'portal' },
  { search: /Website/g, replace: 'Portal' },
  { search: /levitation field/ig, replace: 'portal' },
  { search: /Levitation field/g, replace: 'Portal' },
  { search: /digital experiences/ig, replace: 'etheric networks' },
  { search: /Digital experiences/g, replace: 'Etheric networks' },
  { search: /warp metrics/ig, replace: 'etheric networks' },
  { search: /Warp metrics/g, replace: 'Etheric networks' },
  { search: /graphic design/ig, replace: 'occult symbolism' },
  { search: /Graphic design/g, replace: 'Occult symbolism' },
  { search: /Graphic Design/g, replace: 'Occult Symbolism' },
  { search: /quantum levitation/ig, replace: 'occult symbolism' },
  { search: /Quantum levitation/g, replace: 'Occult symbolism' },
  { search: /Quantum Levitation/g, replace: 'Occult Symbolism' },
  { search: /content production/ig, replace: 'propaganda synthesis' },
  { search: /Content production/g, replace: 'Propaganda synthesis' },
  { search: /Content Production/g, replace: 'Propaganda Synthesis' },
  { search: /zero-g engineering/ig, replace: 'propaganda synthesis' },
  { search: /Zero-G engineering/g, replace: 'Propaganda synthesis' },
  { search: /Zero-G Engineering/g, replace: 'Propaganda Synthesis' },
  { search: /brands/ig, replace: 'sigils' },
  { search: /Brands/g, replace: 'Sigils' },
  { search: /quantum vectors/ig, replace: 'sigils' },
  { search: /Quantum vectors/g, replace: 'Sigils' },
  { search: /brand/ig, replace: 'sigil' },
  { search: /Brand/g, replace: 'Sigil' },
  { search: /quantum vector/ig, replace: 'sigil' },
  { search: /Quantum vector/g, replace: 'Sigil' },
  { search: /projects/ig, replace: 'schemes' },
  { search: /Projects/g, replace: 'Schemes' },
  { search: /field trials/ig, replace: 'schemes' },
  { search: /Field trials/g, replace: 'Schemes' },
  { search: /project/ig, replace: 'scheme' },
  { search: /Project/g, replace: 'Scheme' },
  { search: /field trial/ig, replace: 'scheme' },
  { search: /Field trial/g, replace: 'Scheme' },
  { search: /careers/ig, replace: 'initiations' },
  { search: /Careers/g, replace: 'Initiations' },
  { search: /vacancies/ig, replace: 'initiations' },
  { search: /Vacancies/g, replace: 'Initiations' },
  { search: /strategy/ig, replace: 'dogma' },
  { search: /Strategy/g, replace: 'Dogma' },
  { search: /vector mapping/ig, replace: 'dogma' },
  { search: /Vector mapping/g, replace: 'Dogma' },
  { search: /creative/ig, replace: 'esoteric' },
  { search: /Creative/g, replace: 'Esoteric' },
  { search: /resonant/ig, replace: 'esoteric' },
  { search: /Resonant/g, replace: 'Esoteric' },
  { search: /clients/ig, replace: 'adepts' },
  { search: /Clients/g, replace: 'Adepts' },
  { search: /partners/ig, replace: 'adepts' },
  { search: /Partners/g, replace: 'Adepts' },
  { search: /client/ig, replace: 'adept' },
  { search: /Client/g, replace: 'Adept' },
  { search: /partner/ig, replace: 'adept' },
  { search: /Partner/g, replace: 'Adept' },
  { search: /Sherbrooke/g, replace: 'Shadows' },
  { search: /sherbrooke/g, replace: 'shadows' },
  { search: /Quantum Altitude/g, replace: 'Shadows' },
  { search: /quantum altitude/g, replace: 'shadows' },
  { search: /software/ig, replace: 'telemetry' },
  { search: /development/ig, replace: 'synthesis' },
  { search: /developer/ig, replace: 'architect' },
  { search: /Developer/g, replace: 'Architect' },
  
  // Brand name replacements
  { search: /Standish/g, replace: 'The Illuminati' },
  { search: /standish/g, replace: 'illuminati' },
  { search: /Stans/g, replace: 'Initiates' },
  { search: /stans/g, replace: 'initiates' }
];

function translateString(str) {
  if (!str) return str;
  const normalized = str.trim().replace(/\s+/g, ' ');
  if (translationMap[normalized]) {
    const match = str.match(/^(\s*)([\s\S]*?)(\s*)$/);
    return match[1] + translationMap[normalized] + match[3];
  }
  
  // Apply regex-based word replacement fallback
  let translated = str;
  wordReplacements.forEach(item => {
    translated = translated.replace(item.search, item.replace);
  });
  return translated;
}

files.forEach(file => {
  const filePath = path.join(__dirname, 'www.standish.ca', 'en', file);
  if (!fs.existsSync(filePath)) {
    console.log(`Skipping missing file: ${file}`);
    return;
  }
  
  console.log(`Translating file: ${file}`);
  const html = fs.readFileSync(filePath, 'utf8');
  const $ = cheerio.load(html, { xmlMode: false, decodeEntities: false });

  // 1. Process meta tags
  $('meta').each(function() {
    const content = $(this).attr('content');
    if (content) {
      $(this).attr('content', translateString(content));
    }
  });

  // 2. Process page title tag
  $('title').each(function() {
    const titleText = $(this).text();
    $(this).text(translateString(titleText));
  });

  // 3. Process placeholders
  $('[placeholder]').each(function() {
    const val = $(this).attr('placeholder');
    if (val) {
      $(this).attr('placeholder', translateString(val));
    }
  });

  // 4. Process inputs/buttons value attribute
  $('input[type="submit"], input[type="button"], button').each(function() {
    const val = $(this).attr('value');
    if (val) {
      $(this).attr('value', translateString(val));
    }
  });

  // 5. Process logo image source attributes (pointing to custom SVG logo)
  $('img').each(function() {
    const src = $(this).attr('src');
    if (src && src.includes('Logo-Standish')) {
      $(this).attr('src', "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='384' height='47' viewBox='0 0 384 47'%3E%3Ctext x='0' y='35' font-family='zuume, sans-serif' font-size='38' font-weight='900' letter-spacing='4' fill='%23ffffff'%3EILLUMINATI%3C/text%3E%3C/svg%3E");
      $(this).attr('alt', 'Illuminati');
    }
    const dataSrc = $(this).attr('data-src');
    if (dataSrc && dataSrc.includes('Logo-Standish')) {
      $(this).attr('data-src', "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='384' height='47' viewBox='0 0 384 47'%3E%3Ctext x='0' y='35' font-family='zuume, sans-serif' font-size='38' font-weight='900' letter-spacing='4' fill='%23ffffff'%3EILLUMINATI%3C/text%3E%3C/svg%3E");
      $(this).attr('alt', 'Illuminati');
    }
  });

  // 6. Process all visible text nodes
  $('*').contents().each(function() {
    if (this.type === 'text') {
      const parent = $(this).parent();
      let parentTag = '';
      if (parent.length) {
        parentTag = parent[0].name.toLowerCase();
        if (['script', 'style', 'code', 'noscript', 'head'].includes(parentTag)) return;
      }
      
      const originalText = this.data;
      const translatedText = translateString(originalText);
      if (translatedText !== originalText) {
        this.data = translatedText;
      }
    }
  });

  // Save the modified HTML back completely
  fs.writeFileSync(filePath, $.html(), 'utf8');
  console.log(`Finished writing: ${file}`);
});

console.log("Translation complete!");
